//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GCAdminv23Entities : DbContext
    {
        public GCAdminv23Entities()
            : base("name=GCAdminv23Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblActionEventActionMapping> tblActionEventActionMappings { get; set; }
        public virtual DbSet<tblActionEvent> tblActionEvents { get; set; }
        public virtual DbSet<tblAction> tblActions { get; set; }
        public virtual DbSet<tblAirport> tblAirports { get; set; }
        public virtual DbSet<tblAmenity> tblAmenities { get; set; }
        public virtual DbSet<tblAmenityPage> tblAmenityPages { get; set; }
        public virtual DbSet<tblAmenityPageControl> tblAmenityPageControls { get; set; }
        public virtual DbSet<tblAmenityType> tblAmenityTypes { get; set; }
        public virtual DbSet<tblAmenityTypeMapping> tblAmenityTypeMappings { get; set; }
        public virtual DbSet<tblApplicationMenu> tblApplicationMenus { get; set; }
        public virtual DbSet<tblAsset> tblAssets { get; set; }
        public virtual DbSet<tblCastingDevice> tblCastingDevices { get; set; }
        public virtual DbSet<tblCastingDeviceActionDetail> tblCastingDeviceActionDetails { get; set; }
        public virtual DbSet<tblCastingDeviceActionEventDetail> tblCastingDeviceActionEventDetails { get; set; }
        public virtual DbSet<tblCastingDeviceAditionalDetail> tblCastingDeviceAditionalDetails { get; set; }
        public virtual DbSet<tblCastingDeviceTranctionDetail> tblCastingDeviceTranctionDetails { get; set; }
        public virtual DbSet<tblControl> tblControls { get; set; }
        public virtual DbSet<tblCountry> tblCountries { get; set; }
        public virtual DbSet<tblCouponNumber> tblCouponNumbers { get; set; }
        public virtual DbSet<tblCouponPackage> tblCouponPackages { get; set; }
        public virtual DbSet<tblGSItemCategory> tblGSItemCategories { get; set; }
        public virtual DbSet<tblGSRequestsModifierMapping> tblGSRequestsModifierMappings { get; set; }
        public virtual DbSet<tblGSRequestsModifierMapping_22> tblGSRequestsModifierMapping_22 { get; set; }
        public virtual DbSet<tblGSRequestStatu> tblGSRequestStatus { get; set; }
        public virtual DbSet<tblGuest> tblGuests { get; set; }
        public virtual DbSet<tblGuest_old> tblGuest_old { get; set; }
        public virtual DbSet<tblGuestCoupon> tblGuestCoupons { get; set; }
        public virtual DbSet<tblGuestMRService> tblGuestMRServices { get; set; }
        public virtual DbSet<tblGuestPackage> tblGuestPackages { get; set; }
        public virtual DbSet<tblGuestRoomMapping> tblGuestRoomMappings { get; set; }
        public virtual DbSet<tblGuestServiceRequest> tblGuestServiceRequests { get; set; }
        public virtual DbSet<tblGuestSurvey> tblGuestSurveys { get; set; }
        public virtual DbSet<tblGuestWakeup> tblGuestWakeups { get; set; }
        public virtual DbSet<tblHotel> tblHotels { get; set; }
        public virtual DbSet<tblHotelAddress> tblHotelAddresses { get; set; }
        public virtual DbSet<tblHotelAirport> tblHotelAirports { get; set; }
        public virtual DbSet<tblHotelAmenityType> tblHotelAmenityTypes { get; set; }
        public virtual DbSet<tblHotelCastingConfiguration> tblHotelCastingConfigurations { get; set; }
        public virtual DbSet<tblHotelCastingDevice> tblHotelCastingDevices { get; set; }
        public virtual DbSet<tblHotelCastingDeviceDescriptiveName> tblHotelCastingDeviceDescriptiveNames { get; set; }
        public virtual DbSet<tblHotelCastingDeviceTVInputCommand> tblHotelCastingDeviceTVInputCommands { get; set; }
        public virtual DbSet<tblHotelCommunityChannel> tblHotelCommunityChannels { get; set; }
        public virtual DbSet<tblHotelConfigProp> tblHotelConfigProps { get; set; }
        public virtual DbSet<tblHotelDirectory> tblHotelDirectories { get; set; }
        public virtual DbSet<tblHotelGuestService> tblHotelGuestServices { get; set; }
        public virtual DbSet<tblHotelGuestServiceType> tblHotelGuestServiceTypes { get; set; }
        public virtual DbSet<tblHotelHotSOSConfiguration> tblHotelHotSOSConfigurations { get; set; }
        public virtual DbSet<tblHotelKPMConfig> tblHotelKPMConfigs { get; set; }
        public virtual DbSet<tblHotelLanguageConfiguration> tblHotelLanguageConfigurations { get; set; }
        public virtual DbSet<tblHotelLocalAttraction> tblHotelLocalAttractions { get; set; }
        public virtual DbSet<tblHotelMACOUI> tblHotelMACOUIs { get; set; }
        public virtual DbSet<tblHotelMenuItem> tblHotelMenuItems { get; set; }
        public virtual DbSet<tblHotelMenuItemLanguageMapping> tblHotelMenuItemLanguageMappings { get; set; }
        public virtual DbSet<tblHotelMenuItemParentChildLanguageMapping> tblHotelMenuItemParentChildLanguageMappings { get; set; }
        public virtual DbSet<tblHotelMenuItemParentChildMapping> tblHotelMenuItemParentChildMappings { get; set; }
        public virtual DbSet<tblHotelPackage> tblHotelPackages { get; set; }
        public virtual DbSet<tblHotelPackageType> tblHotelPackageTypes { get; set; }
        public virtual DbSet<tblHotelPersonalization> tblHotelPersonalizations { get; set; }
        public virtual DbSet<tblHotelPredefinedRGNETVLAN> tblHotelPredefinedRGNETVLANs { get; set; }
        public virtual DbSet<tblHotelPreference> tblHotelPreferences { get; set; }
        public virtual DbSet<tblHotelRoom> tblHotelRooms { get; set; }
        public virtual DbSet<tblHotelScreenDetail> tblHotelScreenDetails { get; set; }
        public virtual DbSet<tblHotelScreenMapping> tblHotelScreenMappings { get; set; }
        public virtual DbSet<tblHotelScreenPage> tblHotelScreenPages { get; set; }
        public virtual DbSet<tblHotelScreenPageControl> tblHotelScreenPageControls { get; set; }
        public virtual DbSet<tblHotelSTBTVInputCommand> tblHotelSTBTVInputCommands { get; set; }
        public virtual DbSet<tblHotelTemplateThemeValue> tblHotelTemplateThemeValues { get; set; }
        public virtual DbSet<tblHotelTutorialDetail> tblHotelTutorialDetails { get; set; }
        public virtual DbSet<tblHotelTutorialPage> tblHotelTutorialPages { get; set; }
        public virtual DbSet<tblHotelTutorialPageControl> tblHotelTutorialPageControls { get; set; }
        public virtual DbSet<tblHotelTVBrand> tblHotelTVBrands { get; set; }
        public virtual DbSet<tblHotelTVRightsPkg> tblHotelTVRightsPkgs { get; set; }
        public virtual DbSet<tblHotelVLANDetail> tblHotelVLANDetails { get; set; }
        public virtual DbSet<tblHotSOSIssueCategory> tblHotSOSIssueCategories { get; set; }
        public virtual DbSet<tblHotSOSServiceIssue> tblHotSOSServiceIssues { get; set; }
        public virtual DbSet<tblHotSOSServiceIssueCategoryMapping> tblHotSOSServiceIssueCategoryMappings { get; set; }
        public virtual DbSet<tblHotSOSServiceOrder> tblHotSOSServiceOrders { get; set; }
        public virtual DbSet<tblHotwireMessage> tblHotwireMessages { get; set; }
        public virtual DbSet<tblHotwireRoomMessage> tblHotwireRoomMessages { get; set; }
        public virtual DbSet<tblHotwireTemplateMsg> tblHotwireTemplateMsgs { get; set; }
        public virtual DbSet<tblHotwireTemplateMsgControl> tblHotwireTemplateMsgControls { get; set; }
        public virtual DbSet<tblHotwireTemplateMsgPMSMsgMapping> tblHotwireTemplateMsgPMSMsgMappings { get; set; }
        public virtual DbSet<tblItemCategory> tblItemCategories { get; set; }
        public virtual DbSet<tblItemCategoryParentChildMapping> tblItemCategoryParentChildMappings { get; set; }
        public virtual DbSet<tblLanguage> tblLanguages { get; set; }
        public virtual DbSet<tblLocalAttraction> tblLocalAttractions { get; set; }
        public virtual DbSet<tblLocalAttractionMapping> tblLocalAttractionMappings { get; set; }
        public virtual DbSet<tblMasterPackage> tblMasterPackages { get; set; }
        public virtual DbSet<tblMenuItem> tblMenuItems { get; set; }
        public virtual DbSet<tblModifier> tblModifiers { get; set; }
        public virtual DbSet<tblModifierGroup> tblModifierGroups { get; set; }
        public virtual DbSet<tblModifierGroupGSItemsMapping> tblModifierGroupGSItemsMappings { get; set; }
        public virtual DbSet<tblModifierGroupMapping> tblModifierGroupMappings { get; set; }
        public virtual DbSet<tblPackageViewHistory> tblPackageViewHistories { get; set; }
        public virtual DbSet<tblPM> tblPMS { get; set; }
        public virtual DbSet<tblPMSRoomMessage> tblPMSRoomMessages { get; set; }
        public virtual DbSet<tblPreference> tblPreferences { get; set; }
        public virtual DbSet<tblProperty> tblProperties { get; set; }
        public virtual DbSet<tblQuestion> tblQuestions { get; set; }
        public virtual DbSet<tblQuestionOption> tblQuestionOptions { get; set; }
        public virtual DbSet<tblQuestionType> tblQuestionTypes { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblRoomCleanStatu> tblRoomCleanStatus { get; set; }
        public virtual DbSet<tblRoommove> tblRoommoves { get; set; }
        public virtual DbSet<tblRoomSTB> tblRoomSTBs { get; set; }
        public virtual DbSet<tblRoomType> tblRoomTypes { get; set; }
        public virtual DbSet<tblRoomTypePackage> tblRoomTypePackages { get; set; }
        public virtual DbSet<tblRPIActivityTransaction> tblRPIActivityTransactions { get; set; }
        public virtual DbSet<tblRPIActivityTransactionDetail> tblRPIActivityTransactionDetails { get; set; }
        public virtual DbSet<tblRPICastingDeviceMapping> tblRPICastingDeviceMappings { get; set; }
        public virtual DbSet<tblRPISTBMapping> tblRPISTBMappings { get; set; }
        public virtual DbSet<tblRSCategoriesTiming> tblRSCategoriesTimings { get; set; }
        public virtual DbSet<tblScreen> tblScreens { get; set; }
        public virtual DbSet<tblScreen_copy> tblScreen_copy { get; set; }
        public virtual DbSet<tblScreenPageCategory> tblScreenPageCategories { get; set; }
        public virtual DbSet<tblSTBInfo> tblSTBInfoes { get; set; }
        public virtual DbSet<tblSTBStatu> tblSTBStatus { get; set; }
        public virtual DbSet<tblSubscriberService> tblSubscriberServices { get; set; }
        public virtual DbSet<tblSurvey> tblSurveys { get; set; }
        public virtual DbSet<tblSurveyQuestion> tblSurveyQuestions { get; set; }
        public virtual DbSet<tblTemplate> tblTemplates { get; set; }
        public virtual DbSet<tblTemplateSection> tblTemplateSections { get; set; }
        public virtual DbSet<tblTheme> tblThemes { get; set; }
        public virtual DbSet<tblThemeSkinId> tblThemeSkinIds { get; set; }
        public virtual DbSet<tblThemeSkinParameter> tblThemeSkinParameters { get; set; }
        public virtual DbSet<tblThemeSkinValue> tblThemeSkinValues { get; set; }
        public virtual DbSet<tblTimezone> tblTimezones { get; set; }
        public virtual DbSet<tblTVBrand> tblTVBrands { get; set; }
        public virtual DbSet<tblTVInputPortCommand> tblTVInputPortCommands { get; set; }
        public virtual DbSet<tblTVRight> tblTVRights { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblUserActivity> tblUserActivities { get; set; }
        public virtual DbSet<tblUserRole> tblUserRoles { get; set; }
        public virtual DbSet<tblVODdispute> tblVODdisputes { get; set; }
        public virtual DbSet<tblSTBBasicInfo> tblSTBBasicInfoes { get; set; }
    }
}
