//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAmenityPage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAmenityPage()
        {
            this.tblAmenityPageControls = new HashSet<tblAmenityPageControl>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int pagenumber { get; set; }
        public string status { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
        public Nullable<int> fkTemplateid { get; set; }
        public Nullable<int> fkAmenityid { get; set; }
        public string templateImageName { get; set; }
        public string templateImageCavasURL { get; set; }
        public string isDataUptoDate { get; set; }
    
        public virtual tblAmenity tblAmenity { get; set; }
        public virtual tblTemplate tblTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAmenityPageControl> tblAmenityPageControls { get; set; }
    }
}
