//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAsset
    {
        public int id { get; set; }
        public string assetid { get; set; }
        public string assetproviderid { get; set; }
        public string moviename { get; set; }
        public string reducedtitle { get; set; }
        public string sorttitle { get; set; }
        public string url { get; set; }
        public string rating { get; set; }
        public string longrating { get; set; }
        public string language { get; set; }
        public string posterurl { get; set; }
        public string postername { get; set; }
        public string deliveryprofiletype { get; set; }
        public string resourcetype { get; set; }
        public string actorname { get; set; }
        public System.DateTime createddatetime { get; set; }
        public string resourceid { get; set; }
    }
}
