//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCastingDeviceTranctionDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCastingDeviceTranctionDetail()
        {
            this.tblCastingDeviceActionDetails = new HashSet<tblCastingDeviceActionDetail>();
            this.tblCastingDeviceActionEventDetails = new HashSet<tblCastingDeviceActionEventDetail>();
        }
    
        public int id { get; set; }
        public string rpiack { get; set; }
        public System.DateTime rpiackupdateddatetime { get; set; }
        public string status { get; set; }
        public System.DateTime statusupdateddatetime { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCastingDeviceActionDetail> tblCastingDeviceActionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCastingDeviceActionEventDetail> tblCastingDeviceActionEventDetails { get; set; }
    }
}
