//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblControl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblControl()
        {
            this.tblAmenityPageControls = new HashSet<tblAmenityPageControl>();
            this.tblHotelScreenPageControls = new HashSet<tblHotelScreenPageControl>();
            this.tblHotwireTemplateMsgControls = new HashSet<tblHotwireTemplateMsgControl>();
            this.tblHotelTutorialPageControls = new HashSet<tblHotelTutorialPageControl>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string controltype { get; set; }
        public int posid { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
        public Nullable<int> fkTemplateid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAmenityPageControl> tblAmenityPageControls { get; set; }
        public virtual tblTemplate tblTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelScreenPageControl> tblHotelScreenPageControls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotwireTemplateMsgControl> tblHotwireTemplateMsgControls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelTutorialPageControl> tblHotelTutorialPageControls { get; set; }
    }
}
