//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCastingDeviceActionEventDetail
    {
        public int id { get; set; }
        public int fkHotelVLANDetailsCastingDeviceid { get; set; }
        public int fkActionEventid { get; set; }
        public int fkCastingDeviceTranctionDetailsid { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
    
        public virtual tblActionEvent tblActionEvent { get; set; }
        public virtual tblHotelVLANDetail tblHotelVLANDetail { get; set; }
        public virtual tblCastingDeviceTranctionDetail tblCastingDeviceTranctionDetail { get; set; }
    }
}
