//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGuest_old
    {
        public int id { get; set; }
        public string title { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public System.DateTime checkindate { get; set; }
        public System.DateTime expectedcheckoutdate { get; set; }
        public Nullable<System.DateTime> checkoutdate { get; set; }
        public string checkoutstatus { get; set; }
        public string checkouttype { get; set; }
        public Nullable<float> billamount { get; set; }
        public string roomnumber { get; set; }
        public string folionumber { get; set; }
        public string ecallowed { get; set; }
        public string vip { get; set; }
        public string primaryguest { get; set; }
        public int guestcount { get; set; }
        public string eventcode { get; set; }
        public string groupcode { get; set; }
        public string loyaltynumber { get; set; }
        public string emailid { get; set; }
        public string language { get; set; }
        public string phonenumber { get; set; }
        public int age { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string companyname { get; set; }
        public string companyaddress1 { get; set; }
        public string companyaddress2 { get; set; }
        public string companycode { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
        public string wstatus { get; set; }
        public string tvright { get; set; }
    }
}
