//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGSRequestStatu
    {
        public int id { get; set; }
        public Nullable<int> fkGuestServiceRequestsid { get; set; }
        public string adminstatus { get; set; }
        public Nullable<System.DateTime> assigneddatetime { get; set; }
        public Nullable<System.DateTime> completeddatetime { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
        public Nullable<int> assignedToUser { get; set; }
        public Nullable<int> assignedByUser { get; set; }
        public Nullable<int> statusUpdatedByUser { get; set; }
        public string isReAssigned { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblGuestServiceRequest tblGuestServiceRequest { get; set; }
        public virtual tblUser tblUser2 { get; set; }
    }
}
