//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHotSOSServiceOrder
    {
        public int id { get; set; }
        public string hotsosserviceorderid { get; set; }
        public string hotsosserviceorderstatus { get; set; }
        public int fkHotSOSServiceIssueid { get; set; }
        public int fkGuestid { get; set; }
        public string deviceExternalID { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
    
        public virtual tblGuest tblGuest { get; set; }
        public virtual tblHotSOSServiceIssue tblHotSOSServiceIssue { get; set; }
    }
}
