//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHotelHotSOSConfiguration
    {
        public int id { get; set; }
        public string hotsosip { get; set; }
        public string hotsosport { get; set; }
        public string servicecontext { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string serviceurl { get; set; }
        public int fkHotelid { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
    
        public virtual tblHotel tblHotel { get; set; }
    }
}
