//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHotelCastingDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHotelCastingDevice()
        {
            this.tblHotelCastingDeviceTVInputCommands = new HashSet<tblHotelCastingDeviceTVInputCommand>();
            this.tblHotelMACOUIs = new HashSet<tblHotelMACOUI>();
        }
    
        public int id { get; set; }
        public int fkCastingDeviceid { get; set; }
        public int fkHotelid { get; set; }
        public string status { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
    
        public virtual tblCastingDevice tblCastingDevice { get; set; }
        public virtual tblHotel tblHotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelCastingDeviceTVInputCommand> tblHotelCastingDeviceTVInputCommands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelMACOUI> tblHotelMACOUIs { get; set; }
    }
}
