//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHotelScreenDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHotelScreenDetail()
        {
            this.tblHotelScreenPages = new HashSet<tblHotelScreenPage>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public string bgimage { get; set; }
        public string screenxml { get; set; }
        public Nullable<int> fkLanguageid { get; set; }
        public Nullable<int> fkHotelScreenMappingid { get; set; }
        public string status { get; set; }
        public string thumbnailimage { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
    
        public virtual tblHotelScreenMapping tblHotelScreenMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelScreenPage> tblHotelScreenPages { get; set; }
        public virtual tblLanguage tblLanguage { get; set; }
    }
}
