//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHotelCastingConfiguration
    {
        public int id { get; set; }
        public string rgnetbaseurl { get; set; }
        public string rgnetapikey { get; set; }
        public string castinggatewayipapfacing { get; set; }
        public string castinggatewayport { get; set; }
        public string hotelssid { get; set; }
        public int fkHotelid { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
        public string castinggatewayiprpifacing { get; set; }
        public int accountgroupid { get; set; }
        public int usagePlan { get; set; }
    
        public virtual tblHotel tblHotel { get; set; }
    }
}
