//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHotwireRoomMessage
    {
        public int id { get; set; }
        public Nullable<System.DateTime> messsagedatetime { get; set; }
        public string messageto { get; set; }
        public string readstatus { get; set; }
        public System.DateTime readdatetime { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
        public int fkHotwireMessageid { get; set; }
        public int fkHotelRoomid { get; set; }
        public string messagesender { get; set; }
        public string sendstatus { get; set; }
    
        public virtual tblHotelRoom tblHotelRoom { get; set; }
        public virtual tblHotwireMessage tblHotwireMessage { get; set; }
    }
}
