//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHotelVLANDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHotelVLANDetail()
        {
            this.tblCastingDeviceActionDetails = new HashSet<tblCastingDeviceActionDetail>();
            this.tblCastingDeviceActionEventDetails = new HashSet<tblCastingDeviceActionEventDetail>();
            this.tblCastingDeviceAditionalDetails = new HashSet<tblCastingDeviceAditionalDetail>();
            this.tblRPIActivityTransactionDetails = new HashSet<tblRPIActivityTransactionDetail>();
            this.tblRPICastingDeviceMappings = new HashSet<tblRPICastingDeviceMapping>();
            this.tblRPICastingDeviceMappings1 = new HashSet<tblRPICastingDeviceMapping>();
            this.tblRPISTBMappings = new HashSet<tblRPISTBMapping>();
        }
    
        public int id { get; set; }
        public string vlanrgnetid { get; set; }
        public string vlanname { get; set; }
        public string vendor { get; set; }
        public string deviceip { get; set; }
        public string devicemac { get; set; }
        public System.DateTime createdatdatetime { get; set; }
        public System.DateTime expiresatdatetime { get; set; }
        public System.DateTime updatedatdatetime { get; set; }
        public int fkHotelRoomid { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
        public string devicename { get; set; }
        public string castingdevicename { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCastingDeviceActionDetail> tblCastingDeviceActionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCastingDeviceActionEventDetail> tblCastingDeviceActionEventDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCastingDeviceAditionalDetail> tblCastingDeviceAditionalDetails { get; set; }
        public virtual tblHotelRoom tblHotelRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRPIActivityTransactionDetail> tblRPIActivityTransactionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRPICastingDeviceMapping> tblRPICastingDeviceMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRPICastingDeviceMapping> tblRPICastingDeviceMappings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRPISTBMapping> tblRPISTBMappings { get; set; }
    }
}
