//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHotelMenuItemParentChildMapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHotelMenuItemParentChildMapping()
        {
            this.tblHotelMenuItemParentChildLanguageMappings = new HashSet<tblHotelMenuItemParentChildLanguageMapping>();
        }
    
        public int id { get; set; }
        public int sequence { get; set; }
        public int fkHotelParentMenuItemid { get; set; }
        public int fkHotelChildMenuItemid { get; set; }
        public string status { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
    
        public virtual tblHotelMenuItem tblHotelMenuItem { get; set; }
        public virtual tblHotelMenuItem tblHotelMenuItem1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelMenuItemParentChildLanguageMapping> tblHotelMenuItemParentChildLanguageMappings { get; set; }
    }
}
