//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHotSOSServiceIssue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHotSOSServiceIssue()
        {
            this.tblHotSOSServiceIssueCategoryMappings = new HashSet<tblHotSOSServiceIssueCategoryMapping>();
            this.tblHotSOSServiceOrders = new HashSet<tblHotSOSServiceOrder>();
        }
    
        public int id { get; set; }
        public string hotsosissueid { get; set; }
        public string name { get; set; }
        public string status { get; set; }
        public int fkHotelid { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
    
        public virtual tblHotel tblHotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotSOSServiceIssueCategoryMapping> tblHotSOSServiceIssueCategoryMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotSOSServiceOrder> tblHotSOSServiceOrders { get; set; }
    }
}
