//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHotwireTemplateMsgControl
    {
        public int id { get; set; }
        public Nullable<int> fkHotwireTemplateMsgid { get; set; }
        public Nullable<int> fkControlsid { get; set; }
        public string value { get; set; }
        public string controlHtml { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
    
        public virtual tblControl tblControl { get; set; }
        public virtual tblHotwireTemplateMsg tblHotwireTemplateMsg { get; set; }
    }
}
