//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHotel()
        {
            this.tblCouponNumbers = new HashSet<tblCouponNumber>();
            this.tblHotelAirports = new HashSet<tblHotelAirport>();
            this.tblHotelAmenityTypes = new HashSet<tblHotelAmenityType>();
            this.tblHotelCommunityChannels = new HashSet<tblHotelCommunityChannel>();
            this.tblHotelConfigProps = new HashSet<tblHotelConfigProp>();
            this.tblHotelDirectories = new HashSet<tblHotelDirectory>();
            this.tblHotelGuestServices = new HashSet<tblHotelGuestService>();
            this.tblHotelLocalAttractions = new HashSet<tblHotelLocalAttraction>();
            this.tblHotelMenuItems = new HashSet<tblHotelMenuItem>();
            this.tblHotelPackages = new HashSet<tblHotelPackage>();
            this.tblHotelPersonalizations = new HashSet<tblHotelPersonalization>();
            this.tblHotelPreferences = new HashSet<tblHotelPreference>();
            this.tblHotelRooms = new HashSet<tblHotelRoom>();
            this.tblHotelScreenMappings = new HashSet<tblHotelScreenMapping>();
            this.tblHotelTemplateThemeValues = new HashSet<tblHotelTemplateThemeValue>();
            this.tblHotelTVRightsPkgs = new HashSet<tblHotelTVRightsPkg>();
            this.tblItemCategories = new HashSet<tblItemCategory>();
            this.tblModifiers = new HashSet<tblModifier>();
            this.tblModifierGroups = new HashSet<tblModifierGroup>();
            this.tblQuestions = new HashSet<tblQuestion>();
            this.tblSTBStatus = new HashSet<tblSTBStatu>();
            this.tblSurveys = new HashSet<tblSurvey>();
            this.tblThemes = new HashSet<tblTheme>();
            this.tblUsers = new HashSet<tblUser>();
            this.tblHotelCastingConfigurations = new HashSet<tblHotelCastingConfiguration>();
            this.tblHotelCastingDevices = new HashSet<tblHotelCastingDevice>();
            this.tblHotelCastingDeviceDescriptiveNames = new HashSet<tblHotelCastingDeviceDescriptiveName>();
            this.tblHotelHotSOSConfigurations = new HashSet<tblHotelHotSOSConfiguration>();
            this.tblHotelKPMConfigs = new HashSet<tblHotelKPMConfig>();
            this.tblHotelLanguageConfigurations = new HashSet<tblHotelLanguageConfiguration>();
            this.tblHotelPredefinedRGNETVLANs = new HashSet<tblHotelPredefinedRGNETVLAN>();
            this.tblHotelSTBTVInputCommands = new HashSet<tblHotelSTBTVInputCommand>();
            this.tblHotelTutorialDetails = new HashSet<tblHotelTutorialDetail>();
            this.tblHotelTVBrands = new HashSet<tblHotelTVBrand>();
            this.tblHotSOSServiceIssues = new HashSet<tblHotSOSServiceIssue>();
            this.tblRPIActivityTransactions = new HashSet<tblRPIActivityTransaction>();
        }
    
        public int id { get; set; }
        public string hotelid { get; set; }
        public string hotelname { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string enablevalet { get; set; }
        public string pmsmessagepriority { get; set; }
        public int fkHotelAddressid { get; set; }
        public int fkpmsid { get; set; }
        public string hotelflagshipid { get; set; }
        public string status { get; set; }
        public string managementcompanyid { get; set; }
        public string hoteldescription { get; set; }
        public string weathercode { get; set; }
        public string jsonurl { get; set; }
        public Nullable<int> fkTimezoneid { get; set; }
        public string disableWakeup { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
        public string ecallowed { get; set; }
        public string showWelcomeScreen { get; set; }
        public string showLanguageScreen { get; set; }
        public string notifySurveyPopup { get; set; }
        public string allowFETutorial { get; set; }
        public string enableCasting { get; set; }
        public string applyMainMenuImgAsBackgroundImg { get; set; }
        public string allowdefaultCheckout { get; set; }
        public Nullable<System.TimeSpan> defaultCheckoutTime { get; set; }
        public string enableHotSOS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCouponNumber> tblCouponNumbers { get; set; }
        public virtual tblHotelAddress tblHotelAddress { get; set; }
        public virtual tblPM tblPM { get; set; }
        public virtual tblTimezone tblTimezone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelAirport> tblHotelAirports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelAmenityType> tblHotelAmenityTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelCommunityChannel> tblHotelCommunityChannels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelConfigProp> tblHotelConfigProps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelDirectory> tblHotelDirectories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelGuestService> tblHotelGuestServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelLocalAttraction> tblHotelLocalAttractions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelMenuItem> tblHotelMenuItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelPackage> tblHotelPackages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelPersonalization> tblHotelPersonalizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelPreference> tblHotelPreferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelRoom> tblHotelRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelScreenMapping> tblHotelScreenMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelTemplateThemeValue> tblHotelTemplateThemeValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelTVRightsPkg> tblHotelTVRightsPkgs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemCategory> tblItemCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblModifier> tblModifiers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblModifierGroup> tblModifierGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuestion> tblQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSTBStatu> tblSTBStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSurvey> tblSurveys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTheme> tblThemes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUser> tblUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelCastingConfiguration> tblHotelCastingConfigurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelCastingDevice> tblHotelCastingDevices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelCastingDeviceDescriptiveName> tblHotelCastingDeviceDescriptiveNames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelHotSOSConfiguration> tblHotelHotSOSConfigurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelKPMConfig> tblHotelKPMConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelLanguageConfiguration> tblHotelLanguageConfigurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelPredefinedRGNETVLAN> tblHotelPredefinedRGNETVLANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelSTBTVInputCommand> tblHotelSTBTVInputCommands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelTutorialDetail> tblHotelTutorialDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelTVBrand> tblHotelTVBrands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotSOSServiceIssue> tblHotSOSServiceIssues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRPIActivityTransaction> tblRPIActivityTransactions { get; set; }
    }
}
