//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHotelScreenPage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHotelScreenPage()
        {
            this.tblHotelScreenPageControls = new HashSet<tblHotelScreenPageControl>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int pagenumber { get; set; }
        public string status { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
        public Nullable<int> fkTemplateid { get; set; }
        public Nullable<int> fkHotelScreenDetailsid { get; set; }
        public string templateImageName { get; set; }
        public string templateImageCavasURL { get; set; }
        public string isDataUptoDate { get; set; }
        public string screenPageCategory { get; set; }
    
        public virtual tblHotelScreenDetail tblHotelScreenDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelScreenPageControl> tblHotelScreenPageControls { get; set; }
        public virtual tblTemplate tblTemplate { get; set; }
    }
}
