//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblItemCategory()
        {
            this.tblGSItemCategories = new HashSet<tblGSItemCategory>();
            this.tblItemCategoryParentChildMappings = new HashSet<tblItemCategoryParentChildMapping>();
            this.tblItemCategoryParentChildMappings1 = new HashSet<tblItemCategoryParentChildMapping>();
            this.tblRSCategoriesTimings = new HashSet<tblRSCategoriesTiming>();
        }
    
        public int id { get; set; }
        public string catname { get; set; }
        public string catthumbnail { get; set; }
        public int fkHotelid { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
        public string status { get; set; }
        public int sequence { get; set; }
        public string level { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGSItemCategory> tblGSItemCategories { get; set; }
        public virtual tblHotel tblHotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemCategoryParentChildMapping> tblItemCategoryParentChildMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemCategoryParentChildMapping> tblItemCategoryParentChildMappings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRSCategoriesTiming> tblRSCategoriesTimings { get; set; }
    }
}
