//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLanguage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLanguage()
        {
            this.tblAmenities = new HashSet<tblAmenity>();
            this.tblApplicationMenus = new HashSet<tblApplicationMenu>();
            this.tblHotelLanguageConfigurations = new HashSet<tblHotelLanguageConfiguration>();
            this.tblHotelMenuItemLanguageMappings = new HashSet<tblHotelMenuItemLanguageMapping>();
            this.tblHotelMenuItemParentChildLanguageMappings = new HashSet<tblHotelMenuItemParentChildLanguageMapping>();
            this.tblHotelPersonalizations = new HashSet<tblHotelPersonalization>();
            this.tblHotelScreenDetails = new HashSet<tblHotelScreenDetail>();
        }
    
        public int id { get; set; }
        public string languagename { get; set; }
        public string languagecode { get; set; }
        public string description { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAmenity> tblAmenities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblApplicationMenu> tblApplicationMenus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelLanguageConfiguration> tblHotelLanguageConfigurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelMenuItemLanguageMapping> tblHotelMenuItemLanguageMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelMenuItemParentChildLanguageMapping> tblHotelMenuItemParentChildLanguageMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelPersonalization> tblHotelPersonalizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelScreenDetail> tblHotelScreenDetails { get; set; }
    }
}
