//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPackageViewHistory
    {
        public int id { get; set; }
        public System.DateTime starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<int> duration { get; set; }
        public string completed { get; set; }
        public int fkGuestPackagesid { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
    
        public virtual tblGuestPackage tblGuestPackage { get; set; }
    }
}
