//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSTBInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSTBInfo()
        {
            this.tblRoomSTBs = new HashSet<tblRoomSTB>();
            this.tblRPISTBMappings = new HashSet<tblRPISTBMapping>();
        }
    
        public int id { get; set; }
        public string ipaddress { get; set; }
        public string macaddress { get; set; }
        public Nullable<int> serialnumber { get; set; }
        public string guid { get; set; }
        public string modelname { get; set; }
        public string screenresolution { get; set; }
        public string status { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
        public string deviceExternalID { get; set; }
        public string accountexternalid { get; set; }
        public string languagename { get; set; }
        public string languagecode { get; set; }
        public string notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRoomSTB> tblRoomSTBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRPISTBMapping> tblRPISTBMappings { get; set; }
    }
}
