//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSurveyQuestion
    {
        public int id { get; set; }
        public int fkQuestionid { get; set; }
        public int fkSurveyid { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
    
        public virtual tblQuestion tblQuestion { get; set; }
        public virtual tblSurvey tblSurvey { get; set; }
    }
}
