//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblThemeSkinParameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblThemeSkinParameter()
        {
            this.tblThemeSkinValues = new HashSet<tblThemeSkinValue>();
        }
    
        public int id { get; set; }
        public int fkThemeSkinId { get; set; }
        public string valuetype { get; set; }
        public string status { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
        public string parameterskinid { get; set; }
        public string defaultValue { get; set; }
        public string description { get; set; }
    
        public virtual tblThemeSkinId tblThemeSkinId { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblThemeSkinValue> tblThemeSkinValues { get; set; }
    }
}
