//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTVInputPortCommand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTVInputPortCommand()
        {
            this.tblHotelCastingDeviceTVInputCommands = new HashSet<tblHotelCastingDeviceTVInputCommand>();
            this.tblHotelSTBTVInputCommands = new HashSet<tblHotelSTBTVInputCommand>();
        }
    
        public int id { get; set; }
        public string sourceport { get; set; }
        public string command { get; set; }
        public string status { get; set; }
        public int fkTVBrandid { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelCastingDeviceTVInputCommand> tblHotelCastingDeviceTVInputCommands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHotelSTBTVInputCommand> tblHotelSTBTVInputCommands { get; set; }
        public virtual tblTVBrand tblTVBrand { get; set; }
    }
}
