//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblThemeSkinValue
    {
        public int id { get; set; }
        public int fkThemeid { get; set; }
        public int fkThemeSkinParameterid { get; set; }
        public string value { get; set; }
        public string status { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
        public string canvasColorNameValuePairs { get; set; }
    
        public virtual tblTheme tblTheme { get; set; }
        public virtual tblThemeSkinParameter tblThemeSkinParameter { get; set; }
    }
}
