//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPortalV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVODdispute
    {
        public int id { get; set; }
        public Nullable<int> fkGuestPackageid { get; set; }
        public Nullable<int> fkUserid { get; set; }
        public System.DateTime disputedatetime { get; set; }
        public string settlement { get; set; }
        public float amount { get; set; }
        public string remarks { get; set; }
        public System.DateTime createddatetime { get; set; }
        public System.DateTime updateddatetime { get; set; }
    
        public virtual tblGuestPackage tblGuestPackage { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
